name: Continuous Deployment

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node and cache dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Create .env file
        uses: ozaytsev86/create-env-file-action@v1
        with:
          ENV_NG_APP_API_ENDPOINT: ${{ vars.API_ENDPOINT }}

      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn ng -- deploy --no-silent --cname=charkchalk.io --name="Charkchalk" --email=contact@charkchalk.io
